### ISSUE TITLE
Using the `setup` keyword with the VSCode UI

### ISSUE THREAD

**Issue by bvdmitri** [JuliaTesting/ReTestItems.jl#112]
It seems that the `setup` keyword does not work when running from VSCode UI? Is there a workaround for that?

**Comment by nickrobinson251** [comment]
Unfortunately VSCode has an entirely different implementation: it doesn't use ReTestItems.jl at all, it uses https://github.com/julia-vscode/TestItemRunner.jl

We create ReTestItems.jl because we liked the interface but needed an implementation that we could move fast on developing and prioritised CI testing on large projects. One day we'd love there to be only one implementation.

I think VSCode (or at least the underlying package it uses) has _some_ support for "test setups" but i think you would need to ask on that repo for if/when it will be released and available via the VSCode interface (https://github.com/julia-vscode/TestItemRunner.jl/pull/39#issuecomment-1428346527)

**Comment by bvdmitri** [comment]
Thanks for the answer, for now I found a workaround by just using `include` inside of the `@testitem` for the setup. Works both in VSCode UI and in the `] test` command

**Comment by nickrobinson251** [comment]
VS Code now supports the `setup=[...]` keyword, unfortunately with a slightly different interface, see https://discourse.julialang.org/t/new-stable-features-for-the-test-item-framework/118512

we may adopt this interface to stay aligned with VS Code (but TBD) #182
