### ISSUE TITLE
Option to negate tags in runtests

### ISSUE THREAD

**Issue by deltamarnix** [JuliaTesting/ReTestItems.jl#161]
Would it be possible to write a negation when supplying tags to `runtests()`?

For example, I have a `@testitem "do_a_lot" tags=["long"]`, and I only want to run all the tests that are not tagged `long`.
It would be great if I could specify `runtests(tags=["!long"])`, or `runtests(exclude_tags=["long"])`.

I'm referring to this part in the documentation: https://docs.juliahub.com/General/ReTestItems/stable/autodocs/#ReTestItems.runtests

**Comment by deltamarnix** [comment]
As a workaround I have now used prefixes in the name of the test instead: `@testitem "long_do_a_lot"`, and used a Regex: `runtests(name=r"^(?!long_).*")`

**Comment by nickrobinson251** [comment]
Hi, thanks for the suggestion. You can do this by passing a filter function as the first argument to `runtests` e.g.
```julia
not_long(testitem) = !in(:long, testitem.tags)
runtests(not_long)
```
or equivalently
```julia
runtests(ti -> !(:long in ti.tags))
```

i think we decided not to support a way to negate tags, since at that point the log of `name`, `tags` and (a hypothetical) `exclude_tags` gets quite complex, and you're better of just writing the logic in Julia, hence supporting the option to pass a function that filters on the `name` and `tags` directly.

Does that help?
