### ISSUE TITLE
Don't trigger full GC within the time allowed for a test item

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaTesting/ReTestItems.jl#79]
Here in `runtestitem` we log the test as `DONE` but then trigger GC _before returning the result_ meaning the worker can timeout and be killed after a test has passed and be marked as failed because GC took too long

https://github.com/JuliaTesting/ReTestItems.jl/blob/c346b2558042e5db966a20d3652baec1f34886b9/src/ReTestItems.jl#L821-L825

**Comment by quinnj** [comment]
I wonder if it would be enough to just change those lines to:
```julia
Threads.@spawn begin
    GC.gc(true)
    GC.gc(false)
end
```
Maybe @NHDaly or @d-netto could say whether that would be ok? The idea being that the `runtestitem` call would return immediately and we wouldn't get caught hitting a time limit due to these GC calls, but we're still queuing up a GC to happen after the tesitem eval is done.

**Comment by d-netto** [comment]
I think this could still be vulnerable to the timeout issue mentioned above if the spawned task triggers the GC safe-point quickly enough (and thus halts the parent task to run GC).
